name: Build GDExtension
on:
  workflow_call:
  push:

env:
  LIBNAME: godot_gameplay_attributes

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
        # Debug templates
          - platform: linux
            float-precision: single
            arch: x86_64
            target-type: template_debug
            os: ubuntu-20.04

          - platform: windows
            float-precision: single
            arch: x86_32
            target-type: template_debug
            os: windows-latest

          - platform: windows
            float-precision: single
            arch: x86_64
            target-type: template_debug
            os: windows-latest

          - platform: android
            float-precision: single
            arch: arm64
            target-type: template_debug
            os: ubuntu-20.04

          - platform: android
            float-precision: single
            arch: arm32
            target-type: template_debug
            os: ubuntu-20.04

          - platform: android
            float-precision: single
            arch: x86_64
            target-type: template_debug
            os: ubuntu-20.04

          - platform: android
            float-precision: single
            arch: x86_32
            target-type: template_debug
            os: ubuntu-20.04

          - platform: web
            float-precision: single
            arch: wasm32
            target-type: template_debug
            os: ubuntu-20.04

        # Release templates
          - platform: linux
            float-precision: single
            arch: x86_64
            target-type: template_release
            os: ubuntu-20.04

        # Double precision templates
        # Double precision debug templates
          - platform: linux
            float-precision: double
            arch: x86_64
            target-type: template_debug
            os: ubuntu-20.04

          - platform: windows
            float-precision: double
            arch: x86_32
            target-type: template_debug
            os: windows-latest

          - platform: windows
            float-precision: double
            arch: x86_64
            target-type: template_debug
            os: windows-latest

          - platform: android
            float-precision: double
            arch: arm64
            target-type: template_debug
            os: ubuntu-20.04

          - platform: android
            float-precision: double
            arch: arm32
            target-type: template_debug
            os: ubuntu-20.04

          - platform: android
            float-precision: double
            arch: x86_64
            target-type: template_debug
            os: ubuntu-20.04

          - platform: android
            float-precision: double
            arch: x86_32
            target-type: template_debug
            os: ubuntu-20.04

          - platform: web
            float-precision: double
            arch: wasm32
            target-type: template_debug
            os: ubuntu-20.04

        # Double precision release templates
          - platform: linux
            float-precision: double
            arch: x86_64
            target-type: template_release
            os: ubuntu-20.04

          # - platform: windows
          #   float-precision: double
          #   arch: x86_32
          #   target-type: template_release
          #   os: windows-latest

          # - platform: windows
          #   float-precision: double
          #   arch: x86_64
          #   target-type: template_release
          #   os: windows-latest

          # - platform: macos
          #   float-precision: double
          #   arch: universal
          #   target-type: template_release
          #   os: macos-latest

          # - platform: android
          #   float-precision: double
          #   arch: arm64
          #   target-type: template_release
          #   os: ubuntu-20.04

          # - platform: android
          #   float-precision: double
          #   arch: arm32
          #   target-type: template_release
          #   os: ubuntu-20.04

          # - platform: android
          #   float-precision: double
          #   arch: x86_64
          #   target-type: template_release
          #   os: ubuntu-20.04

          # - platform: android
          #   float-precision: double
          #   arch: x86_32
          #   target-type: template_release
          #   os: ubuntu-20.04

          # - platform: ios
          #   float-precision: double
          #   arch: arm64
          #   target-type: template_release
          #   os: macos-latest

          # - platform: web
          #   float-precision: double
          #   arch: wasm32
          #   target-type: template_release
          #   os: ubuntu-20.04
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

# Build
      - name: 🔗 GDExtension Debug Build
        uses: ./.github/actions/build
        with:
          platform: ${{ matrix.platform }}
          arch: ${{ matrix.arch }}
          float-precision: ${{ matrix.float-precision }}
          build-target-type: ${{ matrix.target-type }}

      - name: Windows - Delete compilation files
        if: ${{ matrix.platform == 'windows' }}
        shell: pwsh
        run: |
          Remove-Item bin/* -Include *.exp,*.lib,*.pdb -Force
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: godot_gameplay_attributes-${{ matrix.platform }}-${{ matrix.arch }}-${{ matrix.float-precision }}-${{ matrix.target-type }}
          path: |
            ${{ github.workspace }}/bin/**

  manifest:
    name: Manifest
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: godot_gameplay_attributes.gdextension
          path:
            ${{ github.workspace }}/godot/addons/godot_gameplay_attributes/godot_gameplay_attributes.gdextension

  # Merges all the build artifacts together into a single artifact.
  # If you comment out this step, all the builds will be uploaded individually.
  merge:
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: godot_gameplay_attributes
          pattern: godot_gameplay_attributes*
          delete-merged: true